### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by xw1w1** [Osmerion/gradle-lwjgl3#11]
Hey, where can i get org.lwjgl.input.Mouse?
LWJGL.Core or.. something?

**Comment by TheMrMilchmann** [comment]
Hi @xw1w1, `org.lwjgl.input.Mouse` was part of LWJGL 2 and was removed in LWJGL 3. It was replaced with bindings for GLFW. You might find the [migration guide](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.6-LWJGL3-migration) useful.

**Comment by xw1w1** [comment]
Thank you!
